FROM nginx:alpine

# remove default config
RUN rm -rf /etc/nginx/conf.d/*

# copy custom config
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# create required dirs
RUN mkdir -p /var/cache/nginx /var/run /var/log/nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
