events {}

http {

  upstream tts_backend {
      server tts-app:8080;
  }

  server {

      listen 80;

      location / {
          proxy_pass http://tts_backend;
      }

      location /metrics {
          proxy_pass http://tts_backend/metrics;
      }

      location /health {
          proxy_pass http://tts_backend/health;
      }

  }

}
